### ISSUE TITLE
Add 'namespaces' to currency

### ISSUE THREAD

**Issue by remyvd** [remyvd/NodaMoney#8]
By adding namespace functionality we can support legacy and custom currencies (like BitCoin), besides the ISO currencies. See also the newly implemented CurrencyUnit in Java 8/9.

The default should be ISO, but something like an override would be useful:
````
var eur = Currency.FromCode("EUR");
var xbt = Currency.FromCode("XBT", "Custom"); // or an enum
```

Also think how developers can add there own currencies by registering them. See an example for Cultures in .NET: http://msdn.microsoft.com/en-us/library/ms172469%28v=VS.100%29.aspx.

How should we name the classes? `CurrencyFormatInfo(Builder)`, `MoneyFormatInfo(Builder)`

**Comment by R2D221** [comment]
Hello, I'm interested in using your library, and I think this feature would be very useful for my project, which is a Bitcoin wallet.

About the implementation, I think the class should be named just `CurrencyBuilder`, since it's not just the format that is being built, but the complete definition of the currency.

**Comment by remyvd** [comment]
It's one of the next features I really want to add. Can't give you a promise when its finished, but the plan is to get it into next milestone 0.4.

**Comment by proxio-david** [comment]
Hi, we use NodaMoney in our project and we need support for historical exchange rates. Instead of removing currencies that are no longer in use (eg "LTL" and "LVL"), perhaps you could add a date range for when they are valid? An ExchangeRate should also be dated, since it is only valid for a specific point in time.

**Comment by remyvd** [comment]
The namespace support will fix the historic currencies.

Adding when the currency is/was valid sounds like a logic step, but adds a lot of extra complexity and maintenance. I don't think the benefit will outweigh this (at the moment), but I could be wrong. 

For EchangeRate your right that they should be dated and is something that will come (probably when a ExchangeProvider is going to be implemented).

**Comment by remyvd** [comment]
@proxio-david we re-added LTV and LVL currencies again and marked them with IsObsolete flag, with the [commits today](https://github.com/remyvd/NodaMoney/compare/dbc80c1a7702c42e02c883ce00725adf765296f7...8f3949a7e9adad14c5bdd4d991d5ec580eb9bced) on the development branch. It will be included in the next release of NodaMoney.

Hope this helps.

**Comment by proxio-david** [comment]
Yes, that helps. Thanks!
